[tool.isort]
profile = "black"
line_length = 100
skip = ["build", "dist", ".venv"]

[tool.ruff]
line-length = 100
target-version = "py310"

# IMPORTANT: moved to a lint section (otherwise warning from ruff)
[tool.ruff.lint]
select = ["E","F","I","B","UP","SIM","RUF"]
ignore = ["E501"]
