name: Lint-Ruff

on:
  pull_request:
  push:
    branches: [ main, master ]
  workflow_dispatch:

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install "ruff==0.13.1"

      - name: Ruff lint
        run: |
          ruff check .
          ruff format --check .
